expose instead of ports
ViderumGlobal/ckan-cloud-docker pull request #49
Opened 2019-06-06 11:58 UTC by ciolansteen

Changed yaml files to use expose instead port forwarding. Tested on DO and everything works

2019-06-06 17:42 UTC, akariv commented
@ciolansteen 

1. Please make sure you're changing services that are part of the ckan dependency tree.
2. How would you connect to the ckan service after this change?
3. Please update documentation based on your modifications.

2019-06-12 19:44 UTC, ciolansteen commented
1 - Checked communication between services using expose instead of ports publishing:
     varnish (depends on ckan)
     redis (ckan dependency)
     nginx (depends on ckan - for testing purposes, the port can be forwarded - included in troubleshooting.md)
     solr (ckan dependency)
     datapusher (not depending nor dependency)

     Don't know how to test the services that have different container port from host port.
       jenkins
       cca-operator
       provisioning-api
     Please confirm if it is ok for these services to remain as is. 
     
2 - connecting to services can be done via ssh to the machine where docker is. There's no need to leave other ports open to the host since traefik takes care of exposing 443 and 80.

2019-06-13 07:55 UTC, akariv commented
1. yes, leave as is
2. how would you connect to ckan service (not ssh, http)?
    is traefik exposing any ports at the moment?

2019-06-13 07:56 UTC, ciolansteen commented
yes, both 80 and 443 are exposed by traefik

2019-06-17 08:11 UTC, akariv commented
It doesn't look like it in the docker-compose file...

2019-06-18 08:49 UTC, ciolansteen commented
it was on .docker-compose.vital-strategies-theme.yaml. Now is in .docker-compose-db.yaml

2019-06-18 09:01 UTC, akariv commented on .docker-compose-db.yaml
> +    ports:
why are we reverting this @ciolansteen ?

2019-06-18 09:02 UTC, akariv requested changes
See my comment - seems you last commit added more changes than you intended.

2019-06-19 08:47 UTC, closed without merging