Remove secrets from codebase
ViderumGlobal/ckan-cloud-docker pull request #50
Opened 2019-06-26 13:24 UTC by aluminiumgeek

- remove secrets from codebase
- added a script that generates env secrets
- updated docs

2019-06-26 20:07 UTC, akariv commented
Not sure I see the need in this PR.
None of the secrets here are actual secrets - DB connection strings are trivial exactly because they run inside the same docker deployment and are not exposed to the outside world.

Centralized configuration is even less important as it's used only for local development.

Overall it seems like an unnecessary complication...

2019-06-26 20:07 UTC, akariv requested changes

2019-06-26 20:07 UTC, akariv commented on .docker-compose-db.yaml
> -    environment:
These dbs should not be exposed externally, so pretty pointless to set up authentication here.

2019-06-26 20:07 UTC, akariv commented on .docker-compose-db.yaml
>      - "5432:5432"
This should be `expose` and not `ports` and not expose the port on the host.

2019-06-26 20:07 UTC, akariv commented on .docker-compose-centralized.yaml
> -    - ./docker-compose/ckan-secrets-centralized.sh:/etc/ckan-conf/secrets/secrets-centralized.sh
This file is to be used in local development only, so there's no 'harden' it...

2019-06-27 11:33 UTC, aluminiumgeek commented
> Not sure I see the need in this PR.

The PR is for first task in https://gitlab.com/datopian/tech/issues/62
If we don't really need it, then (sad) let's close it.
@pwalsh what do you think?

2019-07-14 08:04 UTC, merged