Ccd windows philippines
ViderumGlobal/ckan-cloud-docker pull request #73
Opened 2020-06-03 13:19 UTC by gavram

@zelima 

I've finished this task as you requested. What I did?
1. I created two new files:
  * `.docker-compose.vital-strategies-philippines-theme.yaml`
  * `/docker-compose/ckan-conf-templates/vital-strategies-philippines-theme-production.ini.template`
2. Modifications are made in two more files
  * `/ckan/Dockerfile`
  * `docker-compose.yaml`
3. `DEPLOYing.md` is refactored

The resulting CKAN instance with Vital Strategies theme in browser on host Windows Server 2008 looks as on following screenshot

![image](https://user-images.githubusercontent.com/12686547/83640858-0630ad00-a5ad-11ea-8cfa-02c58192628b.png)

The instance is tested:
1. creating new org
2. creating new goup
3. creating new dataset
4. uploading new resource
5. updating resource
and all is working well.

2020-06-05 10:41 UTC, zelima commented on DEPLOYING.md
> +---
Think we don't need this

2020-06-05 10:43 UTC, gavram commented on DEPLOYING.md
> +---
I'll remove that lines

2020-06-05 11:09 UTC, zelima requested changes

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +Installation of CCD Vital Strategies Philippines on Ubuntu 18.04 LTS inside Virtual Box VM
Maybe 
> Installation guide for CKAN instance for Philipines project on ...

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +6. Exposing CKAN Vital Strategies to outside World
Let's either make this table of content or remove. They can simply read as they go along.  No need to list in the begging unless they are clickable that will take you to specific place.

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +## 1. VirtualBox installation
Make this 3rd level heading 

`###`

Also no need of 1.

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 1 - Download VirtualBox installer for Windows
Remove numbers

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 2 - Run the installer and follow the instructions
Remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 3 – Custom setup dialog box
Remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +If you wish to change the installation directory, you van change it by clicking on the browse button and selecting the new directory and clicking OK. Normally I leave it as the default as the whole i
> van -?

Let's not leave them the choice but give exact directives... Smth like, just leave everything to defaults..

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Custom setup dialog box screenshot
What is this about?

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 4 – Custom setup dialog box – Feature to install
Remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +In this dialog box you can choose which features to install. As you can see, there is not much to choose. You can accept the default and click next. You can uncheck Create a shortcut in the quick lau
Just say accept default

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Custom Setup – Select feature to Install
Is this title (and one above)? If so make it 3 level heading

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 5 – Network Interface setup
Remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Network Interface warning
The same here make it 3rd level heading if is title

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 6 – Ready to Install
same

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Ready to Install
same

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 7 – Installation begins
Same

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 8 – Installation Completes
same

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +After the installation completes, you will see installation completion dialog box. Click finish. If you leave Start Oracle VM VirtualBox after installation checked, VirtualBox will launch automatical
same here don't leave them a choice. Just say what to do

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
No need of these

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
remove these

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
remove

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +## 4. Additional settings for Ubuntu in VM
remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 1. Git installation
make it 3rd level heading

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 1. Git installation
and remove number

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +#### 2. `docker-compose` installation
remove the number and make it 3rd level

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +## 5. CCD Vital Strategies installation
remove number

Say CKAN installation (they don't have clue what is CCD vital strategies :) )

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +git checkout ccd-windows-philippines
Think they can directly clone the branch, Smth like

```
git clone -b <<branch-name>> url
```

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +4. Run
Say why run. Eg `To create secrets run`

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +5. Run
say `Build the image and start the application`

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +  * **`ckan/Dockerfile`** - line #61
I'm still concerned about this part. Let's either make it 2.8.X from the begging or debug. What happens if you have 2.8.X all the time?

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
remove this

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +## 6. Exposing CKAN Vital Strategies to outside World
Remove number and say "Expose CKAN to the outside world."

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +### 2. Using `bridge adapter` method
Let's pick one of them... This one's suggested by Adam as much as I remember so let's keep this

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
remove

2020-06-05 11:09 UTC, zelima commented on DEPLOYING.md
> +---
remove

2020-06-05 11:09 UTC, zelima commented on ckan/Dockerfile
> +RUN CKAN_BRANCH="${CKAN_BRANCH:-ckan-2.7.3}" && CKAN_REPO="${CKAN_REPO:-ckan/ckan}" &&\
Let's have 2.8.1 (at least here). It will be overridden if ser in .docker-compos.philiphins..

2020-06-05 11:09 UTC, zelima commented on docker-compose.yaml
> +        CKAN_BRANCH: ${CKAN_BRANCH:-ckan-2.7.3}
same here, worst case set it in .docker-compose.override...

2020-06-09 09:58 UTC, gavram commented
@zelima I refactored the installation procedure. I made the changes you requested. Everything is tested several times and all is working well - better than in previous procedure.
Also, I've corrected formatting in `DEPLOYING.md` file and made some simplifications in the procedure.

2020-06-09 10:38 UTC, zelima commented on DEPLOYING.md
> +If you wish to change the installation directory, you van change it by clicking on the browse button and selecting the new directory and clicking OK. Normally I leave it as the default as the whole i
@gavram How about this?

2020-06-09 10:38 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Custom setup dialog box screenshot
Also this

2020-06-09 10:39 UTC, zelima commented on DEPLOYING.md
> +In this dialog box you can choose which features to install. As you can see, there is not much to choose. You can accept the default and click next. You can uncheck Create a shortcut in the quick lau
^

2020-06-09 10:39 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Custom Setup – Select feature to Install
^

2020-06-09 10:40 UTC, zelima commented on DEPLOYING.md
> +VirtualBox Installation – Network Interface warning
^

2020-06-09 10:40 UTC, zelima commented on DEPLOYING.md
> +After the installation completes, you will see installation completion dialog box. Click finish. If you leave Start Oracle VM VirtualBox after installation checked, VirtualBox will launch automatical
^

2020-06-09 10:40 UTC, zelima commented on DEPLOYING.md
> +5. Run
^

2020-06-09 10:47 UTC, zelima commented
@gavram missed a few comments. marked with ^

2020-06-10 05:44 UTC, gavram commented
@zelima I've fixed content of `DEPLOYING.md` file that I missed in previous commit.

2020-06-10 06:35 UTC, merged