[master][l]: Removes all the files except README.md
ViderumGlobal/ckan-cloud-docker pull request #78
Opened 2020-08-31 14:38 UTC by MuhammadIsmailShahzad

Removes all the files and updates the README.md with links to the new dedicated branches.
Fixes https://gitlab.com/datopian/tech/devops/-/issues/118
The master branch is now only going to contain links to the dedicated branches of the projects. Links to the projects can be added or removed from the README.md as required.

The README.md now looks like this
![Screenshot from 2020-08-31 19-37-26](https://user-images.githubusercontent.com/57398621/91732281-773e2b80-ebc1-11ea-86ea-e2397fdeafde.png)

2020-09-01 06:37 UTC, zelima requested changes
@MuhammadIsmailShahzad so you are deleting all the files? Let' don't do that. Keep all the files (esp travis related). remove files that are related to specific instances like vital-strategies or similar. 

Also, we need one generic example (you can keep data gov one and maybe rename to datopian or similar...)

2020-09-01 06:37 UTC, zelima commented on .docker-compose-cache-from.yaml
> -version: '3.2'
Why are you deleting this file?

2020-09-01 06:37 UTC, zelima commented on .docker-compose-cache-from.yaml
> -version: '3.2'
Worst case we should make this generic. Example kind of...

2020-09-01 06:37 UTC, zelima commented on .docker-compose-centralized.yaml
> -version: '3.2'
Same - don't delete but make it generic.

2020-09-01 06:37 UTC, zelima commented on .gitignore
> -# Byte-compiled / optimized / DLL files
Why deleting this file?

2020-09-01 06:37 UTC, zelima commented on .travis.sh
> -#!/usr/bin/env bash
same - Why deleting this file?

2020-09-01 06:37 UTC, zelima commented on .travis-ci-operator.yaml
> -encryptedDockerPassword: KNKc72qckJRJxSLzxPEWDGKUSIlUvoOWOdtQopoie9MGv9VUjvzL5kwqOkNkYN5ONZU8RIzVRHywf787zC/qjdYoAOP4ZlDOTHszmIRj39uBAqu3qfri+KAqqG/mkt5xeBa0qNJHphmqEDofsplaDh9xkssvWvbABl8gJ8PyOzTwM5
same - Why deleting this file?

2020-09-02 13:10 UTC, MuhammadIsmailShahzad commented
WONTFIX. Closing this PR. Will open with fixes implemented in a fresh fork.

2020-09-02 13:10 UTC, closed without merging